from . import AddRemoveElementsPage
from . import BasicAuthPage
from . import ChallengingDOMPage
from . import CheckboxesPage
from . import ContextMenuPage
from . import DigestAuthPage
from . import DragAndDropPage
from . import DropdownPage
from . import DynamicControlsPage
from . import EntryAdPage
from . import FileDownloadPage
from . import FileUploadPage
from . import FormAuthPage